---
title: "discriminating-words"
author: "Rochelle Terman"
date: "June 24, 2015"
output: html_document
---

## 0. Prepare
```{r}
#read in CSV file
documents <-read.csv("Data/shelbysessions.csv", header=TRUE)
# turn into corpus
docs <- Corpus(VectorSource(documents$text))
# create DTM
dtm <- create_matrix(docs[["text"]], language="english", removeNumbers=TRUE,
                       stemWords=TRUE, removeSparseTerms=.9, toLower = TRUE, 
                       removePunctuation = TRUE)

```

## 1. Standardized Mean Difference

This is one method to calculate discriminating words. There are many ways to do this. Here we use a standardized mean difference score. It's like a difference of proportion analysis but normalized, as per the following equation:

First we have to split the data.frame to two DTMs from the two authors.

```{r}
# Subset into 2 dtms
shelby <- subset(dtm,document_author=="Shelby",select = -document_author) # should have 1102 obs.
sessions <- subset(dtm,document_author=="Sessions",select = -document_author) # should have 236 obs.
```

Then we calculate the scores. 

```{r}
# calculate means and vars
n.shelby <- sum(colSums(shelby))
n.sessions <- sum(colSums(sessions))
means.shelby <- colMeans(shelby)
var.shelby <- colVars(as.matrix(shelby))
means.sessions <- colMeans(sessions)
var.sessions <- colVars(as.matrix(sessions))
  
#calculate overall score
score <- (means.shelby - means.sessions) / sqrt((var.shelby/n.shelby) + (var.sessions/n.sessions))

# sort and view
score <- sort(score)
head(score,10) # top session words
tail(score,10) # top shelby words
```
